### ISSUE TITLE
Ranging interval property defined inconsistently across FiRa CSML and UCI specifications

### ISSUE THREAD

**Issue by abeltrano** [microsoft/nearobject-framework#37]
**Describe the bug**
The FiRa CSML specification v1.0.0, section 7.5.3.3 UWB Session Data, Table 53, page 106, defines the `RANGING_INTERVAL` property of the `CONFIGURATION_PARAMETERS` field as having 2 bytes:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/2082148/214373761-77331b67-0cab-43f4-ac61-9bfe327a19b5.png">

The FiRa UCI specification v1.1.0, section 8.3 Application Configuration Parameters, Table 29, page 41, defines `RANGING_INTERVAL` as 4 bytes:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/2082148/214373860-666b4aa6-d7f9-4e28-9874-101685473216.png">

Likely only one of them is correct. We need to determine which is correct and align on that value.

**Version Information**
- [FiRa CSML specification v1.0.0](https://groups.firaconsortium.org/wg/members/document/previewpdf/2454)
- [FiRa UCI specification v1.1.0](https://groups.firaconsortium.org/wg/members/document/previewpdf/1949)

**Comment by corbin-phipps** [comment]
I have been informed that the 4-byte value specified in the FiRa UCI specification v1.1.0 is the correct value for this field. However, I have been advised to keep both values since FiRa CSML specification v1.0.0 is already approved. This shouldn't be too big of a deal since the 2-byte CSML version would be the value we get first over OOB, so we can simply append 2 blank bytes when sending the value over UCI.
